---
# This playbook creates database, DB users with remote login

# MariaDB Configuration
- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ morpheus['customOptions']['databasePassword'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ morpheus['customOptions']['databaseUserName'] }}"
    password: "{{ morpheus['customOptions']['databasePassword'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ morpheus['customOptions']['databasePassword'] }}"
    priv: "*.*:ALL,GRANT"
    host: "%"
    state: present

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ morpheus['customOptions']['databaseUserName'] }}"
    password: "{{ morpheus['customOptions']['databasePassword'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ morpheus['customOptions']['databasePassword'] }}"
    priv: "*.*:ALL,GRANT"
    host: localhost
    state: present

- name: create database
  mysql_db:
    name: "{{ morpheus['customOptions']['databaseName'] }}"
    login_user: "{{ morpheus['customOptions']['databaseUserName'] }}"
    login_password: "{{ morpheus['customOptions']['databasePassword'] }}"
    state: present

# Restart MariaDB Service
- name: Restart MariaDB service
  service:
    name: mariadb
    state: restarted
  become: true

